language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include: 
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update

install:
    - composer update --no-interaction --prefer-dist

script: 
    - vendor/bin/phpunit
